### PR TITLE
Add configs for a wayland base install.

### PR DESCRIPTION
**Pull request by 01micko**
These are individual commits as requested but still one pull request. 

I'll add to it as needed.

### CODE REVIEW

**Comment by 01micko** [comment]
Uploaded a package - https://01micko.github.io/tree.html

Next to fix netinstall and we can start testing!

**Comment by johnraff** [comment]
This all looks good!

Reflecting on what seemed to be your original proposal to create a new **bunsen-configs-wbase** package. That now makes a lot of sense to me - it would keep the two ecosystems separated and the X configs could carry on unaffected while the -wbase package would be freeer to do its own thing.

That would mean you'd need to edit this PR though. Maybe easier if I create the new package in the bunsen-configs source first? Initially as a clone of bunsen-configs, but you could then import whetever you saw fit there.

**Comment by 01micko** [comment]
Sorry @johnraff missed this! But for darn good reason :)

I will tag @johanmalm here because of the following youtube video.. not possible without :)

https://youtu.be/SwC3Hpf4rr4

Posted a [link](https://forums.bunsenlabs.org/viewtopic.php?pid=135972#p135972) on the forum as well.

Many thanks to you both! I'm so happy I discovered Labwc in 2021 for Puppy Linux and @dimkr is carrying on the development.

Open source rocks!

**Comment by johanmalm** [comment]
Have put thoughts here: https://forums.bunsenlabs.org/viewtopic.php?pid=136031#p136031

**Comment by johnraff** [comment]
@johanmalm many thanks - your input is always helpful.

**Pull request closed without merging**
