### PR TITLE
Tweaked BunsenLabs_Grey desktop.

### PR DESCRIPTION
**Pull request by Head-on-a-Stick**
I've changed the wallpaper to a grey tile because I could see banding on the grey Beam version.

This desktop is using the new tintrc-grey & BL-Grey.conkyrc that I have just added.

Does everybody approve of these changes?

### CODE REVIEW

**Comment by tknomanzr** [comment]
I left in the old Hydrogen colors in the ~/.Xresources,  just commented out.  Also, Terminator should have a profile with the Hydrogen colors as well. I am not sure if this will help you with the gray themes but I do feel like we should offer a monochrome scheme for those folks who just don't want to change.

**Comment by johnraff** [comment]
I think this goes well beyond "tweaking" into a new theme in its own right, which is what I suggest you make. BunsenLabs_Grey is meant to be a desaturated version of the standard Helium look, different only in its lack of colour. Your theme is well worth adding for people who like the flat look.

New BLOB themes will be picked up by the script automatically if the files are in place.

However, it won't work as-is because many file paths need adjusting. See the other pre-packaged themes. Various places are different from what users would generate for themselves. Likewise the "Saved at Sun  4 Mar 20:39:02 GMT 2018" message which should have been "Released with BunsenLabs Helium" to match the others.

(If you have the graphics abilities I lack, I wonder if you could generate better grey versions of the two Beam wallpapers to go in bunsen-images?)

**Comment by 2ion** [comment]
Good points. I think it's important that our desktop looks fine on most
devices,  so upping the wallpaper density and/or size by a couple of
bytes should be o-kay.

**Comment by Head-on-a-Stick** [comment]
@johnraff:

> BunsenLabs_Grey is meant to be a desaturated version of the standard Helium look, different only in its lack of colour.

I am confused.

On the forums, I said:

> I will probably try to add a "Helium Grey" version because I'm a big fan of monochrome themes.

https://forums.bunsenlabs.org/viewtopic.php?pid=68711#p68711

To which you replied:

> There is already a "BunsenLabs_Grey" which is meant to be that very thing. 

The extant "BunsenLabs_Grey" option is most certainly _not_ monchrome — it has a green panel, green terminal and a green conky.

I could rename my version "BunsenLabs_Mono" I suppose but that just looks confusing (IMO).

The idea of my configuration is to try to replicate the desktop as it would have been had we decided not to add colour for the Helium release.

In respect of the banding, I think this is a colour depth issue and we can't fix it without recreating the Beam wallpaper from scratch with a full 32-bit monochrome range.

I don't know how to do that.

**Comment by Head-on-a-Stick** [comment]
> many file paths need adjusting

Ooops! I will get on that right away...

Thanks!

**Comment by johnraff** [comment]
> @johnraff:
>     BunsenLabs_Grey is meant to be a desaturated version of the standard Helium look, different only in its lack of colour.
> 
> I am confused.
> On the forums, I said:
> 
>     I will probably try to add a "Helium Grey" version because I'm a big fan of monochrome themes.
> 
> https://forums.bunsenlabs.org/viewtopic.php?pid=68711#p68711
> 
> To which you replied:
> 
>     There is already a "BunsenLabs_Grey" which is meant to be that very thing.
> 
> The extant "BunsenLabs_Grey" option is most certainly not monchrome — it has a green panel, green terminal and a green conky.

First off, these preconfigured BLOB themes were originally made by @capn-damo . I have tweaked them a bit though: there were similar problems with filepaths from the auto-generated code, and some things had been left unconfigured, so I added eg ~/.Xresources to try to match.

You're right about tint2, conky and urxvt not being grey (terminator is though). Urxvt was an oversight on my part, which should be fixed. At the time there was no grey tint2 or conky available - I was a bit unhappy with their greenness but didn't feel like messing with Damo's theme any more than that. Now that you've made grey tint2 and conkys I think they should be used here. (I don't know why Damo dropped the tint2 launcher for this one btw - I think it should go back to match the default desktop.)

Anyway, what I thought BunsenLabs_Grey was meant to be was a grey version of the default BL desktop look, but grey not green. That is really the same as your concept of "to try to replicate the desktop as it would have been had we decided not to add colour for the Helium release", but the result is clearly not the same. I think we have slightly different ideas of how grey a theme has to be to call itself "grey", or where the BL desktop would have gone if it wasn't coloured. 

Perhaps we should change the name to **Helium_Beam_Grey**? Whatever we do, the *icons* - systray and launchers especially - remain rather colourful. Is there a grey version of Paper anywhere? 

To be honest, I would still be happier if we kept the existing theme (but with grey tint2, conky and urxvt, and hopefully reprocessed wallpaper images available from bunsen-images), and your own theme, which is very nice in its own right but quite different-looking IMO, added with its own name. 

If you're OK with that, it leaves two tasks:

1) Have a look at our Beam wallpapers - green and grey both - in bunsen-images, and see if they can be improved. I think @hhhorb got the original files from deviantart, with the artist's permission.

2) I'm going just now to have a look at BLOB to see if it would be easy for it to look in /usr/share/bunsen/configs/blob for themes as well as in ~/.config/blob. That would make it easier to add or edit themes, and avoid stuffing 690kB of files into users' $HOME. I certainly don't want to extensively refactor Damo's code though, so only if it looks simple.

**Comment by johnraff** [comment]
I've opened a PR on **bunsen-utilities** with a revised version of bl-obthemes: https://github.com/BunsenLabs/bunsen-utilities/pull/62 I've done a quick test, but confirmation would of course be nice. Copy bl-obthemes into eg your ~/bin, and ~/.config/blob into /usr/share/bunsen/utilities Try deleting the local themes, and the system ones should still be usable, but not deletable.

If that is used, then /usr/share/bunsen/skel/.config/blob, shipped by **bunsen-configs** will no longer be needed. I have provisionally copied over the config files as they are, but of course any changes we are discussing here would ultimately need to be moved over there. The advantage is that we can push out improvements in a package upgrade, because the preset themes will not be in $HOME.

**Comment by Head-on-a-Stick** [comment]
> If you're OK with that

Yes, of course, that's fine.

I will have a look at the images later and see if I can do anything with them.

**Comment by johnraff** [comment]
I have opened an issue on **bunsen-images** about the wallpaper banding problem: https://github.com/BunsenLabs/bunsen-images/issues/9 if you'd like to comment there.

As @2ion says, we should have our desktop looking nice on modern devices.

**Comment by johnraff** [comment]
@Head-on-a-Stick To try to keep the original grey theme I renamed it to Helium_Beam_Grey, hoping that your BunsenLabs_Grey could then be imported as a new theme. Unfortunately git makes this process somewhat complicated - I can't find a way to do it, keeping the history of your commits, without getting your theme renamed to Helium_Beam_Grey and the two merged!

What I can do is go back to the helium-dev branch and `git checkout helium-dev_grey -- skel/.config/blob/BunsenLabs_Grey/ skel/.config/blob/BunsenLabs_Grey.jpg` That will copy in your theme as a new commit, so all your messages will be lost. The best I can do is add a "Head_on_a_Stick" credit to the commit message. Would that be OK?

Or is there a better way to handle this?

**Pull request closed without merging**
