### PR TITLE
Use ellipsis for an incomplete command

### PR DESCRIPTION
**Pull request by yecril23pl**
The command **Run program…** pops up a request for an argument, therefore its label should end with an ellipsis.

### CODE REVIEW

**Comment by johnraff** [comment]
The label phrasing is entirely at the whim of the GUI designers.

**Comment by yecril23pl** [comment]
Everything in a project is technically at the whim of the project managers.  Successful projects have managers who do not trust their whims, preferring to consider arguments instead.

**Comment by johnraff** [comment]
There are many places in the BunsenLabs code base which could be improved. All constructive suggestions are gratefully received.

**Comment by yecril23pl** [comment]
The takeaway is that I shall have to maintain my own fork because I find your *whims* unacceptable (your word, not mine).  I shall still notify you about things I suppose you might want to reconsider, via pull requests because they are the most accurate way to communicate desired changes, not because I am pushy.  You are free to reject them, of course.  I shall try not to repeat myself though, it is not my purpose to annoy you or to disrupt your work.

**Pull request closed without merging**
