### PR TITLE
skel/.config/compton.conf: shadow-exclude jgmenu

### PR DESCRIPTION
**Pull request by johanmalm**

### CODE REVIEW

**Comment by johnraff** [comment]
Hello @johanmalm thank you for this.
Actually, we are just about to commit a new compton.conf, with a list of shadow excludes essentially the same as in Arch: https://git.archlinux.org/svntogit/community.git/tree/trunk/compton.conf?h=packages/compton#n80

```
shadow-exclude = [
    "! name~=''",
    "name = 'Notification'",
    "name = 'Plank'",
    "name = 'Docky'",
    "name = 'Kupfer'",
    "name = 'xfce4-notifyd'",
    "name *= 'VLC'",
    "name *= 'compton'",
    "name *= 'Chromium'",
    "name *= 'Chrome'",
    "class_g = 'Conky'",
    "class_g = 'Kupfer'",
    "class_g = 'Synapse'",
    "class_g ?= 'Notify-osd'",
    "class_g ?= 'Cairo-dock'",
    "class_g ?= 'Xfce4-notifyd'",
    "class_g ?= 'Xfce4-power-manager'",
    "_GTK_FRAME_EXTENTS@:c"
];
```
Will a new line `"name = 'jgmenu'",` be enough?
If so, I could add it myself and close this pull request.

**Comment by johanmalm** [comment]
Thanks. That's great 
Yes, just name=  is enough

**Comment by johnraff** [comment]
Done in **bunsen-configs 9.3.3-1** 
https://github.com/BunsenLabs/bunsen-configs/blob/helium-dev/skel/.config/compton.conf

**Comment by johanmalm** [comment]
Thanks

**Pull request closed without merging**
