### PR TITLE
Palette fix for the default Terminator color profile. This should fix…

### PR DESCRIPTION
**Pull request by tknomanzr**
This should fix the issue with ugly ncurses dialogs. I also modified the .Xresources colors to match. Added a profile Hydrogen to the Terminator profiles that has the Bunsenlabs Hydrogen colors.

### CODE REVIEW

**Comment by Head-on-a-Stick** [comment]
This PR reverts some recent changes made to ~/.Xresources: we decided to remove the xscreensaver stuff and your file calls the old Faenza icon theme instead of our new Paper set.

Would it be possible to re-base the colour changes against the current helium-dev version of ~/.Xresources?

**Comment by tknomanzr** [comment]
Yes. I will fix it. This was why I wanted someone to review it before we merge the PR.

**Comment by Head-on-a-Stick** [comment]
Sorry! That was a mistake.

**Comment by tknomanzr** [comment]
The commit message got mangled somehow but the new version of ~/.Xresources is built against the helium-dev version now. I stashed your suggested git workflow back because it makes sense to make temporary mergeable branches when multiple people are working within the same repository. At some point, we may want to put that workflow into the main README to assist new developers.

**Pull request closed without merging**
