### PR TITLE
skel/.config/jgmenu/prepend.csv: add magnifying glass

### PR DESCRIPTION
**Pull request by johanmalm**

### CODE REVIEW

**Comment by johanmalm** [comment]
[https://youtu.be/UtFiM6dFuLo](https://youtu.be/UtFiM6dFuLo)

**Comment by hhhorb** [comment]
Oh, hell yes. Thanks malm!

**Comment by johnraff** [comment]
Thank you - achieving perfection one small step at a time...

**Comment by johanmalm** [comment]
:-)

**Comment by johanmalm** [comment]
:smile:

**Pull request merged**
