### PR TITLE
Deuterium

### PR DESCRIPTION
**Pull request by Head-on-a-Stick**
Added some comments to .Xresources to explain the custom colourscheme and make it easier to change and added a section to .profile set the console colours.

### CODE REVIEW

**Comment by Head-on-a-Stick** [comment]
Are there any objections to me merging this?

I have another change to add :)

**Comment by johnraff** [comment]
Sorry, I'd forgotten about this one.

1) To me, the .Xresources changes are a good improvement.

2) What should change after adding the .profile code? Under what circumstances will the colours appear in a tty?

**Comment by Head-on-a-Stick** [comment]
> What should change after adding the .profile code? Under what circumstances will the colours appear in a tty?

The console colours will be changed after the user logs into a console screen, the colours will remain stock until the user logs in but that TTY will retain those colour settings after logout. The colourisation only applies to the console in which login took place, all other TTYs remain unaffected.

I like to use the console from time to time and the stock colours are very garish and quite hard to read for my ageing eyes, I think the urxvt colourscheme used by BL is a big improvement for TTY fans.

**Comment by johnraff** [comment]
Sorry, my question was meant to be: what will cause *any* colours to appear on the tty? General commands and man pages appear in white on black for me. When do these "garish" stock colours of which you speak appear? 

I want to compare the appearance of the default setup with your suggested config.

**Comment by Head-on-a-Stick** [comment]
Ah yes, of course, sorry.

Try `htop`, that shows off the colours quite well.

I have a nifty colourtest script here: https://github.com/Head-on-a-Stick/configs/blob/master/colours

Screenshot: https://scrot.moe/image/hiFb

**Comment by johnraff** [comment]
Ah yes of course htop - that shows the colours OK and indeed your suggested config is easier on the eyes. If it matches the default BL urxvt settings, so much the better.

Let's merge!

**Pull request merged**
