### PR TITLE
Lithium jgmenu proposal

### PR DESCRIPTION
**Pull request by johanmalm**
Okay. Let's try again :sweat_smile:

### CODE REVIEW

**Comment by hhhorb** [comment]
From #91 

I didn't have gcc installed.'sudo apt install gcc`

That's working but I have the default theme, I guess I need to configure it. The default is quite lovely, btw, though I wish it opened under the cursor instead of fixed top-left.

**Comment by hhhorb** [comment]
I'd also recommend dropping transparency from the default config and leave that to the user to enable.

**Comment by hhhorb** [comment]
Right, that is fabulous.

Screenshot_2019-04-28_12-07-50

```
#stay_alive = 1
#hide_on_startup = 0
#csv_cmd = pmenu
#tint2_look = 1
at_pointer = 1
#edge_snap_x = 30
#terminal_exec = x-terminal-emulator
#terminal_args = -e
#monitor = 0
#hover_delay = 100
#hide_back_items = 1
#columns = 1
#tabs = 120
#menu_margin_x = 0
#menu_margin_y = 0
#menu_width = 200
#menu_height_min = 0
#menu_height_max = 0
#menu_height_mode = static
menu_padding_top = 0
menu_padding_right = 0
menu_padding_bottom = 0
menu_padding_left = 0
#menu_radius = 1
menu_border = 1
#menu_halign = left
#menu_valign = bottom
#sub_spacing = 1
#sub_padding_top = auto
#sub_padding_right = auto
#sub_padding_bottom = auto
#sub_padding_left = auto
#sub_hover_action = 1
#item_margin_x = 3
#item_margin_y = 3
#item_height = 25
#item_padding_x = 4
#item_radius = 1
#item_border = 0
#item_halign = left
#sep_height = 5
#sep_halign = left
#sep_markup = 
#font = 
#font_fallback = xtg
#icon_size = 22
#icon_text_spacing = 10
icon_theme = Papirus 
#icon_theme_fallback = xtg
#arrow_string = ▸
#arrow_width = 15
color_menu_bg = #23343a 100
color_menu_border = #346077 100
color_norm_bg = #23343a 10
color_norm_fg = #d3dae3 100
color_sel_bg = #346077 100
color_sel_fg = #ffffff 100
color_sel_border = #346077 100
#color_sep_fg = #ffffff 20
#color_scroll_ind = #eeeeee 40
#csv_name_format = %n (%g)
#csv_single_window = 0
#csv_no_dirs = 0
#csv_i18n = 
```

Great. Just... great!

**Comment by johanmalm** [comment]
@hhhorb That looks awesome. The whole scrot is fab. You’ve really an eye for this.

Yes, transparency rarely makes sense for a menu. I’m reluctant to change the defaults as it interfers with backward compatibility. Maybe I’ll gradually phase it out :smile:

What font is that your using on the panel

**Comment by johanmalm** [comment]
@hhhorb if you run

‘jgmenu init -i’

and then choose ‘t’, you can try a few built in themes. I’d be delighted to add a hhh one.

**Comment by hhhorb** [comment]
That's a Futura rip-off, it's my system font and the conky font as well. Futura Bk BT...

http://fontsgeek.com/fonts/Futura-Bk-BT-Book

For my terminal and editor font, I use OCR-B...

https://packages.debian.org/buster/fonts-ocr-b

OCR-A is also a favorite, the font used for routing codes and account numbers on US bank checks.

I love me some '70s/'80s movie computer fonts!

**Comment by johnraff** [comment]
Since this code is not going to be used in Helium, would you consider changing the csv_cmd from pmenu to lx?

...or is that irrelevant to the (lx-apps) submenu?

**Comment by johnraff** [comment]
The "BL pipes" submenu: I'm in two minds about this. Hiding the pipemenus does make the overall appearance cleaner, but OTOH those menus are supposed to make graphics/media/etc apps more accessible. In a lower level like this, theyRe really no more useful than just diving into the "applications" menu. In fact, I wonder if there's a case for just dropping the graphics, multimedia, browser and office pipemenus? But this is really a topic for the forum...

Also, for some reason, at least in a QEMU VM, the "graphics" pipemenu is very reluctant to open. In fact, the *top* item is unreliable, confirmed by switching "graphics" with "multimedia".

**Comment by johnraff** [comment]
At the top of the main menu there's an unwanted blank space, above the separator line. Removing the separator had no effect.

**Comment by hhhorb** [comment]
Thanks for mentioning the font, there's line #44...

`font = Futura Bk BT normal 10`

**Comment by hhhorb** [comment]
jgmenu init -i helps a lot!

You'll get your hhh configs, fret not. :)

**Comment by johanmalm** [comment]
> Since this code is not going to be used in Helium, would you consider changing the csv_cmd from pmenu to lx?
> 
> ...or is that irrelevant to the (lx-apps) submenu?

Maybe it makes more sense to add a proposed lithium-rc1 theme to the jgmenu repo. This way, users on Stretch and Buster can try it out before we commit to the bunsen-configs/lithium branch.

If we take that approach it would be best leaving it as pmenu for the time being.

**Comment by johanmalm** [comment]
> The "BL pipes" submenu: I'm in two minds about this. Hiding the pipemenus does make the overall appearance cleaner, but OTOH those menus are supposed to make graphics/media/etc apps more accessible. In a lower level like this, theyRe really no more useful than just diving into the "applications" menu. In fact, I wonder if there's a case for just dropping the graphics, multimedia, browser and office pipemenus? But this is really a topic for the forum...
> 
> Also, for some reason, at least in a QEMU VM, the "graphics" pipemenu is very reluctant to open. In fact, the _top_ item is unreliable, confirmed by switching "graphics" with "multimedia".

This got sorted in 
https://github.com/johanmalm/jgmenu/commit/633fd42e5dc8c41683d4e4b397ab5657b67bd771

I should upversion really :)

**Comment by johanmalm** [comment]
> At the top of the main menu there's an unwanted blank space, above the separator line. Removing the separator had no effect.

I think your referring to the search box. Does it not say Search... at the top? Have you changed font colour?

If it is what I think is, I fixed it in 

https://github.com/johanmalm/jgmenu/commit/c278f6f726646a44e3dbc96fd051fa1e4e7ca615

**Comment by johanmalm** [comment]
@hhhorb 
Thanks for fonts.
I have been side-tracked playing with wayland for a while.

It looks like lubuntu are going with mir and devault's qtlayershell.

I'm thinking of having a go at implementing a simplified openbox replacement using the wlroots library. We could make it "lab" specific to suit our needs :smile:

**Comment by hhhorb** [comment]
@malm, let me know if I should split any of these issues off to a new issue post.

To recap, theming is as easy as...

```jgmenu init -i```

"t">choose hydrogen, for example>"q". Then...

```jgmenu init --apply-obtheme```

And boom goes the dynamite, an on-the-fly-themeable drop-in replacement for the Openbox menu!

Screenshot_2019-04-30_02-48-41

**Comment by johnraff** [comment]
> the "graphics" pipemenu is very reluctant to open. In fact, the _top_ item is unreliable, confirmed by switching "graphics" with "multimedia".

> At the top of the main menu there's an unwanted blank space, above the separator line. Removing the separator had no effect.

Both above issues have been fixed with the upgrade to v3.0 - many thanks!

**Pull request closed without merging**
