### PR TITLE
Lithium

### PR DESCRIPTION
**Pull request by johanmalm**
Good morning @johnraff 
A couple of commits to move to the new 'apps' module.
'apps' is the way forward - in my mind anyway.
It should sort out the issue that you and @hhhorb had when the menu didn't refresh when you installed a new application (I think you tried mousepad - if you remember).

### CODE REVIEW

**Comment by johnraff** [comment]
Tested on VM with jgmenu 4.0 and working fine. Newly installed gpicview appeared on menu immediately.
Many thanks!

**Comment by johanmalm** [comment]
That’s great. Thanks for confirming.

**Comment by hhhorb** [comment]
Wait, so it's done? Jgmenu auto-updates when new programs are installed?

WOOHOOOOOO!!!!!

Sorry, I just sat on the cat. w00t

**Comment by johanmalm** [comment]
:smile:
Steady progress...

**Comment by hhhorb** [comment]
Dudes, you guys rock.

**Comment by hhhorb** [comment]
Also, confirmed. Edit the file and you immediately have auto-updates, no logout or restart of any program required. Nice.

**Pull request merged**
