### PR TITLE
Lithium jgmenu proposal

### PR DESCRIPTION
**Pull request by johanmalm**
Hi @johnraff 

Proposed menu for Lithium.

For the time being it uses pmenu to make it easier to test for those still on Stretch.

[https://youtu.be/JD0nRJFi9ZI](https://youtu.be/JD0nRJFi9ZI)

One of the widget features requires the latest commit on the 'master' branch.

I'll post something public on the forums when we've released the next version of jgmenu

### CODE REVIEW

**Comment by johnraff** [comment]
@johanmalm Thanks for this!
Unfortunately, it's against the helium branch, and would break installs if applied and uploaded.

I'm closing this, could you resend it against the lithium branch?

**Comment by johnraff** [comment]
Meanwhile, I'll try the suggested jgmenu on a Lithium test machine.

**Comment by hhhorb** [comment]
The install from the master repo fails for me on lithium...

```
roy@TyrellCorp:~$ git clone https://github.com/johanmalm/jgmenu.git
Cloning into 'jgmenu'...
remote: Enumerating objects: 6150, done.
remote: Total 6150 (delta 0), reused 0 (delta 0), pack-reused 6150
Receiving objects: 100% (6150/6150), 1.57 MiB | 1.24 MiB/s, done.
Resolving deltas: 100% (4168/4168), done.
roy@TyrellCorp:~$ cd jgmenu
roy@TyrellCorp:~/jgmenu$ ./scripts/install-debian-dependencies.sh                 
info: installing build dependencies for jgmenu...
[sudo] password for roy: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  freetype2-doc gir1.2-harfbuzz-0.0 gir1.2-rsvg-2.0 icu-devtools javascript-common
  libblkid-dev libcairo-script-interpreter2 libdpkg-perl libexpat1-dev libffi-dev
  libfile-fcntllock-perl libfm-extra4 libfontconfig1-dev libfreetype6-dev
  libfribidi-dev libgdk-pixbuf2.0-bin libgdk-pixbuf2.0-dev libglib2.0-dev-bin
  libgraphite2-dev libharfbuzz-dev libharfbuzz-gobject0 libharfbuzz-icu0
  libice-dev libicu-dev libjs-jquery libmenu-cache-bin libmenu-cache3 libmount-dev
  libpcre16-3 libpcre3-dev libpcre32-3 libpcrecpp0v5 libpixman-1-dev libpng-dev
  libpng-tools libpthread-stubs0-dev libselinux1-dev libsepol1-dev libsm-dev
  libxau-dev libxcb-render0-dev libxcb-shm0-dev libxcb1-dev libxdmcp-dev
  libxext-dev libxft-dev libxrender-dev pango1.0-tools pkg-config
  python3-distutils python3-lib2to3 uuid-dev x11proto-core-dev x11proto-dev
  x11proto-randr-dev x11proto-xext-dev xorg-sgml-doctools xtrans-dev
Suggested packages:
  apache2 | lighttpd | httpd libcairo2-doc debian-keyring gcc | c-compiler
  binutils patch bzr libglib2.0-doc libxml2-utils libgraphite2-utils libice-doc
  icu-doc libmenu-cache-doc imagemagick libpango1.0-doc librsvg2-doc libsm-doc
  libx11-doc libxcb-doc libxext-doc dpkg-dev
The following NEW packages will be installed:
  freetype2-doc gir1.2-harfbuzz-0.0 gir1.2-rsvg-2.0 icu-devtools javascript-common
  libblkid-dev libcairo-script-interpreter2 libcairo2-dev libdpkg-perl
  libexpat1-dev libffi-dev libfile-fcntllock-perl libfm-extra4 libfontconfig1-dev
  libfreetype6-dev libfribidi-dev libgdk-pixbuf2.0-bin libgdk-pixbuf2.0-dev
  libglib2.0-dev libglib2.0-dev-bin libgraphite2-dev libharfbuzz-dev
  libharfbuzz-gobject0 libharfbuzz-icu0 libice-dev libicu-dev libjs-jquery
  libmenu-cache-bin libmenu-cache-dev libmenu-cache3 libmount-dev libpango1.0-dev
  libpcre16-3 libpcre3-dev libpcre32-3 libpcrecpp0v5 libpixman-1-dev libpng-dev
  libpng-tools libpthread-stubs0-dev librsvg2-dev libselinux1-dev libsepol1-dev
  libsm-dev libx11-dev libxau-dev libxcb-render0-dev libxcb-shm0-dev libxcb1-dev
  libxdmcp-dev libxext-dev libxft-dev libxml2-dev libxrandr-dev libxrender-dev
  pango1.0-tools pkg-config python3-distutils python3-lib2to3 uuid-dev
  x11proto-core-dev x11proto-dev x11proto-randr-dev x11proto-xext-dev
  xorg-sgml-doctools xtrans-dev
0 upgraded, 66 newly installed, 0 to remove and 0 not upgraded.
Need to get 28.7 MB of archives.
After this operation, 102 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 https://cdn-aws.deb.debian.org/debian buster/main amd64 libjs-jquery all 3.3.1~dfsg-3 [332 kB]
Get:2 https://cdn-aws.deb.debian.org/debian buster/main amd64 freetype2-doc all 2.9.1-3 [2308 kB]
Get:3 https://cdn-aws.deb.debian.org/debian buster/main amd64 libharfbuzz-gobject0 amd64 2.3.1-1 [848 kB]
Get:4 https://cdn-aws.deb.debian.org/debian buster/main amd64 gir1.2-harfbuzz-0.0 amd64 2.3.1-1 [853 kB]
Get:5 https://cdn-aws.deb.debian.org/debian buster/main amd64 gir1.2-rsvg-2.0 amd64 2.44.10-2 [21.7 kB]
Get:6 https://cdn-aws.deb.debian.org/debian buster/main amd64 icu-devtools amd64 63.1-6 [188 kB]
Get:7 https://cdn-aws.deb.debian.org/debian buster/main amd64 javascript-common all 11 [6120 B]
Get:8 https://cdn-aws.deb.debian.org/debian buster/main amd64 uuid-dev amd64 2.33.1-0.1 [93.6 kB]
Get:9 https://cdn-aws.deb.debian.org/debian buster/main amd64 libblkid-dev amd64 2.33.1-0.1 [225 kB]
Get:10 https://cdn-aws.deb.debian.org/debian buster/main amd64 libcairo-script-interpreter2 amd64 1.16.0-4 [160 kB]
Get:11 https://cdn-aws.deb.debian.org/debian buster/main amd64 libexpat1-dev amd64 2.2.6-1 [152 kB]
Get:12 https://cdn-aws.deb.debian.org/debian buster/main amd64 libpng-dev amd64 1.6.36-5 [300 kB]
Get:13 https://cdn-aws.deb.debian.org/debian buster/main amd64 libfreetype6-dev amd64 2.9.1-3 [543 kB]
Get:14 https://cdn-aws.deb.debian.org/debian buster/main amd64 libdpkg-perl all 1.19.6 [1412 kB]
Get:15 https://cdn-aws.deb.debian.org/debian buster/main amd64 pkg-config amd64 0.29-6 [63.5 kB]
Get:16 https://cdn-aws.deb.debian.org/debian buster/main amd64 libfontconfig1-dev amd64 2.13.1-2 [966 kB]
Get:17 https://cdn-aws.deb.debian.org/debian buster/main amd64 xorg-sgml-doctools all 1:1.11-1 [21.9 kB]
Get:18 https://cdn-aws.deb.debian.org/debian buster/main amd64 x11proto-dev all 2018.4-4 [251 kB]
Get:19 https://cdn-aws.deb.debian.org/debian buster/main amd64 x11proto-core-dev all 2018.4-4 [3128 B]
Get:20 https://cdn-aws.deb.debian.org/debian buster/main amd64 libxau-dev amd64 1:1.0.8-1+b2 [23.1 kB]
Get:21 https://cdn-aws.deb.debian.org/debian buster/main amd64 libxdmcp-dev amd64 1:1.1.2-3 [42.2 kB]
Get:22 https://cdn-aws.deb.debian.org/debian buster/main amd64 xtrans-dev all 1.3.5-1 [100 kB]
Get:23 https://cdn-aws.deb.debian.org/debian buster/main amd64 libpthread-stubs0-dev amd64 0.4-1 [5344 B]
Get:24 https://cdn-aws.deb.debian.org/debian buster/main amd64 libxcb1-dev amd64 1.13.1-2 [174 kB]
Get:25 https://cdn-aws.deb.debian.org/debian buster/main amd64 libx11-dev amd64 2:1.6.7-1 [827 kB]
Get:26 https://cdn-aws.deb.debian.org/debian buster/main amd64 libxrender-dev amd64 1:0.9.10-1 [40.8 kB]
Get:27 https://cdn-aws.deb.debian.org/debian buster/main amd64 x11proto-xext-dev all 2018.4-4 [3128 B]
Get:28 https://cdn-aws.deb.debian.org/debian buster/main amd64 libxext-dev amd64 2:1.3.3-1+b2 [107 kB]
Get:29 https://cdn-aws.deb.debian.org/debian buster/main amd64 libice-dev amd64 2:1.0.9-2 [66.8 kB]
Get:30 https://cdn-aws.deb.debian.org/debian buster/main amd64 libsm-dev amd64 2:1.2.3-1 [38.0 kB]
Get:31 https://cdn-aws.deb.debian.org/debian buster/main amd64 libpixman-1-dev amd64 0.36.0-1 [554 kB]
Get:32 https://cdn-aws.deb.debian.org/debian buster/main amd64 libxcb-render0-dev amd64 1.13.1-2 [112 kB]
Get:33 https://cdn-aws.deb.debian.org/debian buster/main amd64 libxcb-shm0-dev amd64 1.13.1-2 [100 kB]
Get:34 https://cdn-aws.deb.debian.org/debian buster/main amd64 libffi-dev amd64 3.2.1-9 [156 kB]
Get:35 https://cdn-aws.deb.debian.org/debian buster/main amd64 python3-lib2to3 all 3.7.3~rc1-1 [76.7 kB]
Get:36 https://cdn-aws.deb.debian.org/debian buster/main amd64 python3-distutils all 3.7.3~rc1-1 [142 kB]
Get:37 https://cdn-aws.deb.debian.org/debian buster/main amd64 libglib2.0-dev-bin amd64 2.58.3-1 [157 kB]
Get:38 https://cdn-aws.deb.debian.org/debian buster/main amd64 libmount-dev amd64 2.33.1-0.1 [232 kB]
Get:39 https://cdn-aws.deb.debian.org/debian buster/main amd64 libpcre16-3 amd64 2:8.39-12 [259 kB]
Get:40 https://cdn-aws.deb.debian.org/debian buster/main amd64 libpcre32-3 amd64 2:8.39-12 [250 kB]
Get:41 https://cdn-aws.deb.debian.org/debian buster/main amd64 libpcrecpp0v5 amd64 2:8.39-12 [152 kB]
Get:42 https://cdn-aws.deb.debian.org/debian buster/main amd64 libpcre3-dev amd64 2:8.39-12 [650 kB]
Get:43 https://cdn-aws.deb.debian.org/debian buster/main amd64 libsepol1-dev amd64 2.8-1 [338 kB]
Get:44 https://cdn-aws.deb.debian.org/debian buster/main amd64 libselinux1-dev amd64 2.8-1+b1 [169 kB]
Get:45 https://cdn-aws.deb.debian.org/debian buster/main amd64 libglib2.0-dev amd64 2.58.3-1 [1482 kB]
Get:46 https://cdn-aws.deb.debian.org/debian buster/main amd64 libcairo2-dev amd64 1.16.0-4 [734 kB]
Get:47 https://cdn-aws.deb.debian.org/debian buster/main amd64 libfile-fcntllock-perl amd64 0.22-3+b5 [35.4 kB]
Get:48 https://cdn-aws.deb.debian.org/debian buster/main amd64 libfm-extra4 amd64 1.3.1-1 [32.1 kB]
Get:49 https://cdn-aws.deb.debian.org/debian buster/main amd64 libfribidi-dev amd64 1.0.5-3.1 [100 kB]
Get:50 https://cdn-aws.deb.debian.org/debian buster/main amd64 libgdk-pixbuf2.0-bin amd64 2.38.1+dfsg-1 [24.1 kB]
Get:51 https://cdn-aws.deb.debian.org/debian buster/main amd64 libgdk-pixbuf2.0-dev amd64 2.38.1+dfsg-1 [49.5 kB]
Get:52 https://cdn-aws.deb.debian.org/debian buster/main amd64 libgraphite2-dev amd64 1.3.13-7 [23.1 kB]
Get:53 https://cdn-aws.deb.debian.org/debian buster/main amd64 libharfbuzz-icu0 amd64 2.3.1-1 [834 kB]
Get:54 https://cdn-aws.deb.debian.org/debian buster/main amd64 libicu-dev amd64 63.1-6 [9181 kB]
Get:55 https://cdn-aws.deb.debian.org/debian buster/main amd64 libharfbuzz-dev amd64 2.3.1-1 [1307 kB]
Get:56 https://cdn-aws.deb.debian.org/debian buster/main amd64 libmenu-cache-bin amd64 1.1.0-1 [34.4 kB]
Get:57 https://cdn-aws.deb.debian.org/debian buster/main amd64 libmenu-cache3 amd64 1.1.0-1 [19.9 kB]
Get:58 https://cdn-aws.deb.debian.org/debian buster/main amd64 libmenu-cache-dev amd64 1.1.0-1 [45.1 kB]
Get:59 https://cdn-aws.deb.debian.org/debian buster/main amd64 libxft-dev amd64 2.3.2-2 [68.7 kB]
Get:60 https://cdn-aws.deb.debian.org/debian buster/main amd64 pango1.0-tools amd64 1.42.4-6 [55.3 kB]
Get:61 https://cdn-aws.deb.debian.org/debian buster/main amd64 libpango1.0-dev amd64 1.42.4-6 [139 kB]
Get:62 https://cdn-aws.deb.debian.org/debian buster/main amd64 libpng-tools amd64 1.6.36-5 [139 kB]
Get:63 https://cdn-aws.deb.debian.org/debian buster/main amd64 librsvg2-dev amd64 2.44.10-2 [41.8 kB]
Get:64 https://cdn-aws.deb.debian.org/debian buster/main amd64 libxml2-dev amd64 2.9.4+dfsg1-7+b3 [783 kB]
Get:65 https://cdn-aws.deb.debian.org/debian buster/main amd64 x11proto-randr-dev all 2018.4-4 [3132 B]
Get:66 https://cdn-aws.deb.debian.org/debian buster/main amd64 libxrandr-dev amd64 2:1.5.1-1 [45.0 kB]
Fetched 28.7 MB in 28s (1029 kB/s)                                                 
Extracting templates from packages: 100%
Selecting previously unselected package libjs-jquery.
(Reading database ... 173544 files and directories currently installed.)
Preparing to unpack .../00-libjs-jquery_3.3.1~dfsg-3_all.deb ...
Unpacking libjs-jquery (3.3.1~dfsg-3) ...
Selecting previously unselected package freetype2-doc.
Preparing to unpack .../01-freetype2-doc_2.9.1-3_all.deb ...
Unpacking freetype2-doc (2.9.1-3) ...
Selecting previously unselected package libharfbuzz-gobject0:amd64.
Preparing to unpack .../02-libharfbuzz-gobject0_2.3.1-1_amd64.deb ...
Unpacking libharfbuzz-gobject0:amd64 (2.3.1-1) ...
Selecting previously unselected package gir1.2-harfbuzz-0.0:amd64.
Preparing to unpack .../03-gir1.2-harfbuzz-0.0_2.3.1-1_amd64.deb ...
Unpacking gir1.2-harfbuzz-0.0:amd64 (2.3.1-1) ...
Selecting previously unselected package gir1.2-rsvg-2.0:amd64.
Preparing to unpack .../04-gir1.2-rsvg-2.0_2.44.10-2_amd64.deb ...
Unpacking gir1.2-rsvg-2.0:amd64 (2.44.10-2) ...
Selecting previously unselected package icu-devtools.
Preparing to unpack .../05-icu-devtools_63.1-6_amd64.deb ...
Unpacking icu-devtools (63.1-6) ...
Selecting previously unselected package javascript-common.
Preparing to unpack .../06-javascript-common_11_all.deb ...
Unpacking javascript-common (11) ...
Selecting previously unselected package uuid-dev:amd64.
Preparing to unpack .../07-uuid-dev_2.33.1-0.1_amd64.deb ...
Unpacking uuid-dev:amd64 (2.33.1-0.1) ...
Selecting previously unselected package libblkid-dev:amd64.
Preparing to unpack .../08-libblkid-dev_2.33.1-0.1_amd64.deb ...
Unpacking libblkid-dev:amd64 (2.33.1-0.1) ...
Selecting previously unselected package libcairo-script-interpreter2:amd64.
Preparing to unpack .../09-libcairo-script-interpreter2_1.16.0-4_amd64.deb ...
Unpacking libcairo-script-interpreter2:amd64 (1.16.0-4) ...
Selecting previously unselected package libexpat1-dev:amd64.
Preparing to unpack .../10-libexpat1-dev_2.2.6-1_amd64.deb ...
Unpacking libexpat1-dev:amd64 (2.2.6-1) ...
Selecting previously unselected package libpng-dev:amd64.
Preparing to unpack .../11-libpng-dev_1.6.36-5_amd64.deb ...
Unpacking libpng-dev:amd64 (1.6.36-5) ...
Selecting previously unselected package libfreetype6-dev:amd64.
Preparing to unpack .../12-libfreetype6-dev_2.9.1-3_amd64.deb ...
Unpacking libfreetype6-dev:amd64 (2.9.1-3) ...
Selecting previously unselected package libdpkg-perl.
Preparing to unpack .../13-libdpkg-perl_1.19.6_all.deb ...
Unpacking libdpkg-perl (1.19.6) ...
Selecting previously unselected package pkg-config.
Preparing to unpack .../14-pkg-config_0.29-6_amd64.deb ...
Unpacking pkg-config (0.29-6) ...
Selecting previously unselected package libfontconfig1-dev:amd64.
Preparing to unpack .../15-libfontconfig1-dev_2.13.1-2_amd64.deb ...
Unpacking libfontconfig1-dev:amd64 (2.13.1-2) ...
Selecting previously unselected package xorg-sgml-doctools.
Preparing to unpack .../16-xorg-sgml-doctools_1%3a1.11-1_all.deb ...
Unpacking xorg-sgml-doctools (1:1.11-1) ...
Selecting previously unselected package x11proto-dev.
Preparing to unpack .../17-x11proto-dev_2018.4-4_all.deb ...
Unpacking x11proto-dev (2018.4-4) ...
Selecting previously unselected package x11proto-core-dev.
Preparing to unpack .../18-x11proto-core-dev_2018.4-4_all.deb ...
Unpacking x11proto-core-dev (2018.4-4) ...
Selecting previously unselected package libxau-dev:amd64.
Preparing to unpack .../19-libxau-dev_1%3a1.0.8-1+b2_amd64.deb ...
Unpacking libxau-dev:amd64 (1:1.0.8-1+b2) ...
Selecting previously unselected package libxdmcp-dev:amd64.
Preparing to unpack .../20-libxdmcp-dev_1%3a1.1.2-3_amd64.deb ...
Unpacking libxdmcp-dev:amd64 (1:1.1.2-3) ...
Selecting previously unselected package xtrans-dev.
Preparing to unpack .../21-xtrans-dev_1.3.5-1_all.deb ...
Unpacking xtrans-dev (1.3.5-1) ...
Selecting previously unselected package libpthread-stubs0-dev:amd64.
Preparing to unpack .../22-libpthread-stubs0-dev_0.4-1_amd64.deb ...
Unpacking libpthread-stubs0-dev:amd64 (0.4-1) ...
Selecting previously unselected package libxcb1-dev:amd64.
Preparing to unpack .../23-libxcb1-dev_1.13.1-2_amd64.deb ...
Unpacking libxcb1-dev:amd64 (1.13.1-2) ...
Selecting previously unselected package libx11-dev:amd64.
Preparing to unpack .../24-libx11-dev_2%3a1.6.7-1_amd64.deb ...
Unpacking libx11-dev:amd64 (2:1.6.7-1) ...
Selecting previously unselected package libxrender-dev:amd64.
Preparing to unpack .../25-libxrender-dev_1%3a0.9.10-1_amd64.deb ...
Unpacking libxrender-dev:amd64 (1:0.9.10-1) ...
Selecting previously unselected package x11proto-xext-dev.
Preparing to unpack .../26-x11proto-xext-dev_2018.4-4_all.deb ...
Unpacking x11proto-xext-dev (2018.4-4) ...
Selecting previously unselected package libxext-dev:amd64.
Preparing to unpack .../27-libxext-dev_2%3a1.3.3-1+b2_amd64.deb ...
Unpacking libxext-dev:amd64 (2:1.3.3-1+b2) ...
Selecting previously unselected package libice-dev:amd64.
Preparing to unpack .../28-libice-dev_2%3a1.0.9-2_amd64.deb ...
Unpacking libice-dev:amd64 (2:1.0.9-2) ...
Selecting previously unselected package libsm-dev:amd64.
Preparing to unpack .../29-libsm-dev_2%3a1.2.3-1_amd64.deb ...
Unpacking libsm-dev:amd64 (2:1.2.3-1) ...
Selecting previously unselected package libpixman-1-dev:amd64.
Preparing to unpack .../30-libpixman-1-dev_0.36.0-1_amd64.deb ...
Unpacking libpixman-1-dev:amd64 (0.36.0-1) ...
Selecting previously unselected package libxcb-render0-dev:amd64.
Preparing to unpack .../31-libxcb-render0-dev_1.13.1-2_amd64.deb ...
Unpacking libxcb-render0-dev:amd64 (1.13.1-2) ...
Selecting previously unselected package libxcb-shm0-dev:amd64.
Preparing to unpack .../32-libxcb-shm0-dev_1.13.1-2_amd64.deb ...
Unpacking libxcb-shm0-dev:amd64 (1.13.1-2) ...
Selecting previously unselected package libffi-dev:amd64.
Preparing to unpack .../33-libffi-dev_3.2.1-9_amd64.deb ...
Unpacking libffi-dev:amd64 (3.2.1-9) ...
Selecting previously unselected package python3-lib2to3.
Preparing to unpack .../34-python3-lib2to3_3.7.3~rc1-1_all.deb ...
Unpacking python3-lib2to3 (3.7.3~rc1-1) ...
Selecting previously unselected package python3-distutils.
Preparing to unpack .../35-python3-distutils_3.7.3~rc1-1_all.deb ...
Unpacking python3-distutils (3.7.3~rc1-1) ...
Selecting previously unselected package libglib2.0-dev-bin.
Preparing to unpack .../36-libglib2.0-dev-bin_2.58.3-1_amd64.deb ...
Unpacking libglib2.0-dev-bin (2.58.3-1) ...
Selecting previously unselected package libmount-dev:amd64.
Preparing to unpack .../37-libmount-dev_2.33.1-0.1_amd64.deb ...
Unpacking libmount-dev:amd64 (2.33.1-0.1) ...
Selecting previously unselected package libpcre16-3:amd64.
Preparing to unpack .../38-libpcre16-3_2%3a8.39-12_amd64.deb ...
Unpacking libpcre16-3:amd64 (2:8.39-12) ...
Selecting previously unselected package libpcre32-3:amd64.
Preparing to unpack .../39-libpcre32-3_2%3a8.39-12_amd64.deb ...
Unpacking libpcre32-3:amd64 (2:8.39-12) ...
Selecting previously unselected package libpcrecpp0v5:amd64.
Preparing to unpack .../40-libpcrecpp0v5_2%3a8.39-12_amd64.deb ...
Unpacking libpcrecpp0v5:amd64 (2:8.39-12) ...
Selecting previously unselected package libpcre3-dev:amd64.
Preparing to unpack .../41-libpcre3-dev_2%3a8.39-12_amd64.deb ...
Unpacking libpcre3-dev:amd64 (2:8.39-12) ...
Selecting previously unselected package libsepol1-dev:amd64.
Preparing to unpack .../42-libsepol1-dev_2.8-1_amd64.deb ...
Unpacking libsepol1-dev:amd64 (2.8-1) ...
Selecting previously unselected package libselinux1-dev:amd64.
Preparing to unpack .../43-libselinux1-dev_2.8-1+b1_amd64.deb ...
Unpacking libselinux1-dev:amd64 (2.8-1+b1) ...
Selecting previously unselected package libglib2.0-dev:amd64.
Preparing to unpack .../44-libglib2.0-dev_2.58.3-1_amd64.deb ...
Unpacking libglib2.0-dev:amd64 (2.58.3-1) ...
Selecting previously unselected package libcairo2-dev:amd64.
Preparing to unpack .../45-libcairo2-dev_1.16.0-4_amd64.deb ...
Unpacking libcairo2-dev:amd64 (1.16.0-4) ...
Selecting previously unselected package libfile-fcntllock-perl.
Preparing to unpack .../46-libfile-fcntllock-perl_0.22-3+b5_amd64.deb ...
Unpacking libfile-fcntllock-perl (0.22-3+b5) ...
Selecting previously unselected package libfm-extra4:amd64.
Preparing to unpack .../47-libfm-extra4_1.3.1-1_amd64.deb ...
Unpacking libfm-extra4:amd64 (1.3.1-1) ...
Selecting previously unselected package libfribidi-dev:amd64.
Preparing to unpack .../48-libfribidi-dev_1.0.5-3.1_amd64.deb ...
Unpacking libfribidi-dev:amd64 (1.0.5-3.1) ...
Selecting previously unselected package libgdk-pixbuf2.0-bin.
Preparing to unpack .../49-libgdk-pixbuf2.0-bin_2.38.1+dfsg-1_amd64.deb ...
Unpacking libgdk-pixbuf2.0-bin (2.38.1+dfsg-1) ...
Selecting previously unselected package libgdk-pixbuf2.0-dev:amd64.
Preparing to unpack .../50-libgdk-pixbuf2.0-dev_2.38.1+dfsg-1_amd64.deb ...
Unpacking libgdk-pixbuf2.0-dev:amd64 (2.38.1+dfsg-1) ...
Selecting previously unselected package libgraphite2-dev:amd64.
Preparing to unpack .../51-libgraphite2-dev_1.3.13-7_amd64.deb ...
Unpacking libgraphite2-dev:amd64 (1.3.13-7) ...
Selecting previously unselected package libharfbuzz-icu0:amd64.
Preparing to unpack .../52-libharfbuzz-icu0_2.3.1-1_amd64.deb ...
Unpacking libharfbuzz-icu0:amd64 (2.3.1-1) ...
Selecting previously unselected package libicu-dev:amd64.
Preparing to unpack .../53-libicu-dev_63.1-6_amd64.deb ...
Unpacking libicu-dev:amd64 (63.1-6) ...
Selecting previously unselected package libharfbuzz-dev:amd64.
Preparing to unpack .../54-libharfbuzz-dev_2.3.1-1_amd64.deb ...
Unpacking libharfbuzz-dev:amd64 (2.3.1-1) ...
Selecting previously unselected package libmenu-cache-bin.
Preparing to unpack .../55-libmenu-cache-bin_1.1.0-1_amd64.deb ...
Unpacking libmenu-cache-bin (1.1.0-1) ...
Selecting previously unselected package libmenu-cache3:amd64.
Preparing to unpack .../56-libmenu-cache3_1.1.0-1_amd64.deb ...
Unpacking libmenu-cache3:amd64 (1.1.0-1) ...
Selecting previously unselected package libmenu-cache-dev:amd64.
Preparing to unpack .../57-libmenu-cache-dev_1.1.0-1_amd64.deb ...
Unpacking libmenu-cache-dev:amd64 (1.1.0-1) ...
Selecting previously unselected package libxft-dev:amd64.
Preparing to unpack .../58-libxft-dev_2.3.2-2_amd64.deb ...
Unpacking libxft-dev:amd64 (2.3.2-2) ...
Selecting previously unselected package pango1.0-tools.
Preparing to unpack .../59-pango1.0-tools_1.42.4-6_amd64.deb ...
Unpacking pango1.0-tools (1.42.4-6) ...
Selecting previously unselected package libpango1.0-dev:amd64.
Preparing to unpack .../60-libpango1.0-dev_1.42.4-6_amd64.deb ...
Unpacking libpango1.0-dev:amd64 (1.42.4-6) ...
Selecting previously unselected package libpng-tools.
Preparing to unpack .../61-libpng-tools_1.6.36-5_amd64.deb ...
Unpacking libpng-tools (1.6.36-5) ...
Selecting previously unselected package librsvg2-dev:amd64.
Preparing to unpack .../62-librsvg2-dev_2.44.10-2_amd64.deb ...
Unpacking librsvg2-dev:amd64 (2.44.10-2) ...
Selecting previously unselected package libxml2-dev:amd64.
Preparing to unpack .../63-libxml2-dev_2.9.4+dfsg1-7+b3_amd64.deb ...
Unpacking libxml2-dev:amd64 (2.9.4+dfsg1-7+b3) ...
Selecting previously unselected package x11proto-randr-dev.
Preparing to unpack .../64-x11proto-randr-dev_2018.4-4_all.deb ...
Unpacking x11proto-randr-dev (2018.4-4) ...
Selecting previously unselected package libxrandr-dev:amd64.
Preparing to unpack .../65-libxrandr-dev_2%3a1.5.1-1_amd64.deb ...
Unpacking libxrandr-dev:amd64 (2:1.5.1-1) ...
Setting up libpcrecpp0v5:amd64 (2:8.39-12) ...
Setting up libcairo-script-interpreter2:amd64 (1.16.0-4) ...
Setting up javascript-common (11) ...
Setting up libharfbuzz-icu0:amd64 (2.3.1-1) ...
Setting up libpixman-1-dev:amd64 (0.36.0-1) ...
Setting up libpcre16-3:amd64 (2:8.39-12) ...
Setting up libfm-extra4:amd64 (1.3.1-1) ...
Setting up libpng-tools (1.6.36-5) ...
Setting up libfile-fcntllock-perl (0.22-3+b5) ...
Setting up libfribidi-dev:amd64 (1.0.5-3.1) ...
Setting up libpng-dev:amd64 (1.6.36-5) ...
Setting up pango1.0-tools (1.42.4-6) ...
Setting up libsepol1-dev:amd64 (2.8-1) ...
Setting up libharfbuzz-gobject0:amd64 (2.3.1-1) ...
Setting up libffi-dev:amd64 (3.2.1-9) ...
Setting up gir1.2-harfbuzz-0.0:amd64 (2.3.1-1) ...
Setting up libpthread-stubs0-dev:amd64 (0.4-1) ...
Setting up libfreetype6-dev:amd64 (2.9.1-3) ...
Setting up xtrans-dev (1.3.5-1) ...
Setting up libgraphite2-dev:amd64 (1.3.13-7) ...
Setting up libexpat1-dev:amd64 (2.2.6-1) ...
Setting up uuid-dev:amd64 (2.33.1-0.1) ...
Setting up libpcre32-3:amd64 (2:8.39-12) ...
Setting up icu-devtools (63.1-6) ...
Setting up libdpkg-perl (1.19.6) ...
Setting up libgdk-pixbuf2.0-bin (2.38.1+dfsg-1) ...
Setting up xorg-sgml-doctools (1:1.11-1) ...
Setting up libmenu-cache-bin (1.1.0-1) ...
Setting up libjs-jquery (3.3.1~dfsg-3) ...
Setting up gir1.2-rsvg-2.0:amd64 (2.44.10-2) ...
Setting up python3-lib2to3 (3.7.3~rc1-1) ...
Setting up libicu-dev:amd64 (63.1-6) ...
Setting up python3-distutils (3.7.3~rc1-1) ...
Setting up x11proto-dev (2018.4-4) ...
Setting up libglib2.0-dev-bin (2.58.3-1) ...
Setting up libblkid-dev:amd64 (2.33.1-0.1) ...
Setting up libxau-dev:amd64 (1:1.0.8-1+b2) ...
Setting up libice-dev:amd64 (2:1.0.9-2) ...
Setting up libsm-dev:amd64 (2:1.2.3-1) ...
Setting up libpcre3-dev:amd64 (2:8.39-12) ...
Setting up x11proto-randr-dev (2018.4-4) ...
Setting up libxdmcp-dev:amd64 (1:1.1.2-3) ...
Setting up freetype2-doc (2.9.1-3) ...
Setting up libxml2-dev:amd64 (2.9.4+dfsg1-7+b3) ...
Setting up x11proto-core-dev (2018.4-4) ...
Setting up pkg-config (0.29-6) ...
Setting up x11proto-xext-dev (2018.4-4) ...
Setting up libmenu-cache3:amd64 (1.1.0-1) ...
Setting up libmount-dev:amd64 (2.33.1-0.1) ...
Setting up libfontconfig1-dev:amd64 (2.13.1-2) ...
Setting up libxcb1-dev:amd64 (1.13.1-2) ...
Setting up libselinux1-dev:amd64 (2.8-1+b1) ...
Setting up libx11-dev:amd64 (2:1.6.7-1) ...
Setting up libxcb-shm0-dev:amd64 (1.13.1-2) ...
Setting up libglib2.0-dev:amd64 (2.58.3-1) ...
Setting up libxcb-render0-dev:amd64 (1.13.1-2) ...
Setting up libxext-dev:amd64 (2:1.3.3-1+b2) ...
Setting up libxrender-dev:amd64 (1:0.9.10-1) ...
Setting up libxft-dev:amd64 (2.3.2-2) ...
Setting up libxrandr-dev:amd64 (2:1.5.1-1) ...
Processing triggers for libglib2.0-0:amd64 (2.58.3-1) ...
Processing triggers for libc-bin (2.28-8) ...
Processing triggers for man-db (2.8.5-2) ...
Setting up libgdk-pixbuf2.0-dev:amd64 (2.38.1+dfsg-1) ...
Setting up libmenu-cache-dev:amd64 (1.1.0-1) ...
Setting up libcairo2-dev:amd64 (1.16.0-4) ...
Setting up libharfbuzz-dev:amd64 (2.3.1-1) ...
Setting up libpango1.0-dev:amd64 (1.42.4-6) ...
Setting up librsvg2-dev:amd64 (2.44.10-2) ...
roy@TyrellCorp:~/jgmenu$ make
bash: make: command not found
roy@TyrellCorp:~/jgmenu$ sudo apt install make 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  make-doc
The following NEW packages will be installed:
  make
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 341 kB of archives.
After this operation, 1327 kB of additional disk space will be used.
Get:1 https://cdn-aws.deb.debian.org/debian buster/main amd64 make amd64 4.2.1-1.2 [341 kB]
Fetched 341 kB in 6s (52.9 kB/s)         
Selecting previously unselected package make.
(Reading database ... 176598 files and directories currently installed.)
Preparing to unpack .../make_4.2.1-1.2_amd64.deb ...
Unpacking make (4.2.1-1.2) ...
Setting up make (4.2.1-1.2) ...
Processing triggers for man-db (2.8.5-2) ...
roy@TyrellCorp:~/jgmenu$ make
     CHECK build dependencies
     CC    jgmenu.o
/bin/sh: 1: cc: not found
make: *** [Makefile:102: jgmenu.o] Error 127
```

**Comment by johanmalm** [comment]
@johnraff apologies - I'll try again.

@hhhorb Have you got gcc installed?

**Pull request closed without merging**
