### PR TITLE
Finalise conversion of package source format

### PR DESCRIPTION
**Pull request by ghost**
@johnraff Bunch of changes in order to finalise your package format change; please consult debian/changelog for specifics.

One thing we need to talk about is whether we continue installing files into /root. In my opinion, this is generally a bad thing since /root is still user space, and package-provided files have no place there. Also, unless the files installed to /root are explictily registered as configuration files (for files below /etc this happens automagically), the files will get overwritten whenever the package is being updated.

I also removed /etc/skel/.profile, since that file is being provided by the 'bash' package which is labelled essential/always present and the .profile contents this package was shipping were identical to the original ones. That saves us one config file takeover.

### CODE REVIEW

**Comment by johnraff** [comment]
Agreed about files in /root. (I mentioned this here: http://crunchbang.org/forums/viewtopic.php?pid=421011#p421011 ) They do nothing important anyway.

**Comment by johnraff** [comment]
You've added Templates, but we seem to have lost most of the other directories that were in /etc/skel : .fonts .icons .themes bin images & tmp.

**Comment by ghost** [comment]
They got lost! I'll gather the shards and add them again.

**Comment by ghost** [comment]
Since this branch has been closed, I'll be working on another one. What about sbin in path now?

**Comment by ghost** [comment]
@johnraff I don't see the files you mentioned in the tree _before_ I started working on this. These files don't even seem to be in the import from ten days ago -> https://github.com/BunsenLabs/bunsen-configs/tree/f65eca8500dfc8470ba3a50e7effb13b41bad4df/etc/skel

**Comment by johnraff** [comment]
That's strange. They're all in my local repo, even after pulling down your commits of yesterday.
Could it be because all those directories are empty?

**Comment by johnraff** [comment]
Even stranger - on further searching, at some point recently the directory tree has got messed up. 

Now I've got locally:
/home/john/git/bunsen-configs/skel
    containing
    bin  .config  .fonts  .icons  images  .themes  tmp
in which
/home/john/git/bunsen-configs/skel/.config
    contains
    bunsen geany volumeicon
and
/home/john/git/bunsen-configs/.config
with the same contents as GitHub.

.config/geany is in both trees, with different content. The files and directories that should be there have been divided up between the two locations.

On GitHub, skel only contains the recently added volumeicon dir.

**Comment by ghost** [comment]
Hm. I'm not sure if this is applicable, but for one thing, [commiting empty directories requires some extra work](https://stackoverflow.com/questions/115983/how-can-i-add-an-empty-directory-to-a-git-repository). 

For the rest of the problems: May I suggest that you clone the repo again (into a different folder), keeping your current tree, see what you get and add in (git add, git commit) what's been left out? It is very unlikely that this is a bug in git rather than a human mistake :)

**Comment by johnraff** [comment]
Reading that link, it's clear that the empty directories were part of the problem. I'll have to put some kind of dotfile in them. 

I'll start again with a fresh local repo as you suggest.

**Comment by johnraff** [comment]
Adding a .gitignore to empty directories seems to have fixed it.

**Pull request merged**
