### PR TITLE
adding config for HiDPI screens

### PR DESCRIPTION
**Pull request by vinzv**

### CODE REVIEW

**Comment by Head-on-a-Stick** [comment]
We're not using the latest version of tint2 in Helium so the *border_{sides,color_\*}* options and the Executors will cause ~/xsession-errors to fill up.

Helium will use tint2 v0.12.12 so we can only use the options available for that version.

**Comment by vinzv** [comment]
Yeah, I just copied the default tint2rc and changed some values. Maybe leaving the problematic settings there but commenting them out for future reference?

**Comment by Head-on-a-Stick** [comment]
> Maybe leaving the problematic settings there but commenting them out for future reference?

I will have to check if tint2 is actually spamming .xsession-errors (that was a presumption on my part) — if it's not then it would be a nice surprise for users if they upgraded tint2 and their panel configuration took advantage of this automatically.

**Comment by tknomanzr** [comment]
It will, unfortunately. It is something I have intended to mention to o9000 but have not yet done so.

**Comment by johnraff** [comment]
I think those new tint2 settings arrived with Damo's latest versions of tint2rc.
I noticed the error messages in ~/xsession-errors a while ago, but let it be, thinking, like @Head-on-a-Stick :
> actually, maybe leave them in as an Easter Egg for those who upgrade to our backported tint2?

(Upgrading tint2, the gradients do look very nice, and there's a Poweroff button which appears on the right.)

So - tolerate the error messages, or comment out the unsupported items?

Shipping the backported tint2 is tempting too, though it would go against our long-established policy of keeping custom apps to a minimum...

About error messages: of course there's nothing that o9000 can do to change the behaviour of a previous package, but he might some day consider making the current release a little less verbose, and not outputting the non-text escape characters.

**Comment by vinzv** [comment]
I value the policy of keeping custom packages to a minimum very high. Therefore I'd comment the settings out and would prefer trying to get the newer version into Debian's Stretch repos.

**Comment by tknomanzr** [comment]
I think we should comment the entries out as well, perhaps with a comment in the config file that explains that it might be wise to set up a cron job that trims ~/.Xsession-errors for the time being. At least, that is how I have been going about it with my launcher that shows CPU stats in tint2 (because it updates once per second).

**Comment by vinzv** [comment]
I commented the options out and added a note to the file's header.

**Comment by johnraff** [comment]
OK let's merge that.
I will have to check our existing tint2 files and make similar changes before the helium release.

**Comment by johnraff** [comment]
(Debian Stretch has tint2 0.12.12-3 while Buster has 16.2-1 already.)

Actually, our default tint2rc is using other unsupported options than in the hidipi version, for example "**gradient**", "**separator**" and "**button**". 

Meanwhile "border_color{,*}" and "border_sides" are OK, supported since 0.12.3: https://gitlab.com/o9000/tint2/blob/master/doc/tint2.md
As far as I can tell, none of those lines in tint2rc-hidpi should need to be commented out. I just restored them in a VM and see no errors. @Head-on-a-Stick what version of tint2 did you test this file on?

The section from .xsession-errors running *default* tint2rc shows the following unique lines:
```
tint2 : invalid option "gradient",
tint2 : invalid option "start_color",
tint2 : invalid option "end_color",
tint2 : invalid option "color_stop",
tint2 : invalid option "gradient_id",
tint2 : invalid option "separator",
tint2 : invalid option "separator_background_id",
tint2 : invalid option "separator_color",
tint2 : invalid option "separator_padding",
tint2 : invalid option "separator_size",
tint2 : invalid option "separator_style",
tint2 : invalid option "button",
tint2 : invalid option "button_background_id",
tint2 : invalid option "button_centered",
tint2 : invalid option "button_dwheel_command",
tint2 : invalid option "button_font_color",
tint2 : invalid option "button_icon",
tint2 : invalid option "button_lclick_command",
tint2 : invalid option "button_max_icon_size",
tint2 : invalid option "button_mclick_command",
tint2 : invalid option "button_padding",
tint2 : invalid option "button_rclick_command",
tint2 : invalid option "button_text",
tint2 : invalid option "button_tooltip",
tint2 : invalid option "button_uwheel_command",
```
This raises the question:

> I just copied the default tint2rc and changed some values

@vinzv what file did you base tint2rc-hidipi on?

**Comment by vinzv** [comment]
@johnraff I copied the default tint2rc included in Helium Alpha 2 but that is not the problem's root.

I just checked it and found out that tint2conf adds a lot of additional settings no matter what you change yourself as long as you change at least one setting. E.g. I only doubled the panel height and got the resulting file attached: https://gist.github.com/vinzv/86adda1e36de9ed3981e692e8f11c1af

Diff to default tint2rc: https://gist.github.com/vinzv/e2c38b18045e006312e74966739b7a47

So, now we have the situation that either a newer tint2 version is needed or a (presumably) lower version of tint2conf.

**Comment by johnraff** [comment]
tint2conf is part of tint2, so it should always be compatible.

But, I still don't see any problem with the hidpi file you originally provided! The added border_* properties are supported by tint2 0.12.12-3 and I get no error messages in .xsession-errors when using it in a default Helium install. I still don't know why @Head-on-a-Stick was seeing them.

OTOH the default BL tint2rc *does* use unsupported properties, and *does* fill .xsession-errors with messages.

**Comment by tknomanzr** [comment]
I can live with a bit of ~/Xsession-errors spam anyway. Most every other application spams it the same. It is the executors running at a 1s interval that kill me.

**Comment by johnraff** [comment]
OK shall we just leave the other tint2 files as they are, with the unsupported syntax as an Easter egg for upgraders, and live with the error messages? 

That would just leave the [final wallpapers](https://github.com/BunsenLabs/bunsen-images/issues/9#issuecomment-379525301) - and the CD build - as the last things before an official release.

**Comment by Head-on-a-Stick** [comment]
I vote for leaving the configuration in (and uncommented), the Easter egg idea appeals.

**Comment by vinzv** [comment]
I'd leave it in, both commented and uncommented is okay for me.

**Comment by johnraff** [comment]
> Meanwhile "border_color{,*}" and "border_sides" are OK, supported since 0.12.3: https://gitlab.com/o9000/tint2/blob/master/doc/tint2.md
> As far as I can tell, none of those lines in tint2rc-hidpi should need to be commented out. I just restored them in a VM and see no errors.

I still see no problems with the *border_* properties that @vinzv originally put in his file. They are supported (from 0.12.3) by the Debian Stretch default tint2, as is *executor* (from 0.12.4), so uncomment them again?

**Comment by johnraff** [comment]
@vinzv I reverted your commit  f5b5e63 (which commented out the border_* properties), I hope that's OK.

**Comment by vinzv** [comment]
@johnraff Sure thing!

**Pull request merged**
