### PR TITLE
Tweaks to urxvt configuration and bug fix for tint2 systray icon

### PR DESCRIPTION
**Pull request by Head-on-a-Stick**
See https://forums.bunsenlabs.org/viewtopic.php?id=1541 for details of the icon problem.

### CODE REVIEW

**Comment by johnraff** [comment]
@Head-on-a-Stick unfortunately you based this pull request on a branch of the repo that had got out of date, so there are conflicts.

I had already increased the urxvt geometry to 80x28, and set the urxvt icon path to our version at /usr/share/icons/Faenza-Bunsen-common/apps/48/utilities-terminal.png

Thank you for the other useful tweaks and tint2 bugfix.

I will check out your repo locally, merge the commits there and push back to GitHub.
(Personally I feel geometry of 100x30 might be a bit big?)

**Comment by johnraff** [comment]
**bunsen-configs** version pushed to **8.6.15-1**

**Comment by Head-on-a-Stick** [comment]
@John Ooops, sorry about that!

Perhaps you are right about the geometry, use whatever you think is best.

**Comment by johnraff** [comment]
It's only a default value anyway.

**Comment by hhhorb** [comment]
Aces. Thank you, gentlemen.

**Pull request merged**
