### PR TITLE
add bunsenlabs-wayland.desktop

### PR DESCRIPTION
**Pull request by 01micko**
add install routines for bunsenlabs-wayland.desktop and link bunsenlab-session-wayland -> bunsenlabs-session This is enough for a bunsenlabs-wayland choice in netinstall as other files can be added in the netinstall $HOME dir

### CODE REVIEW

**Comment by 01micko** [comment]
@johnraff this is a start, 3 changes in one commit but all related.

It addresses #134  checks 1 and 3

**Comment by johnraff** [comment]
Looks good, except that the wayland-sessions/ dir wants to be under wayland/ to keep all the wayland stuff in one place, for easier maintainance. So the line in debian/bunsen-configs-wayland.install would be `wayland/wayland-sessions usr/share`

In fact all the lines in debian/bunsen-configs-wayland.install will start with wayland/

**Comment by 01micko** [comment]
> Looks good, except that the wayland-sessions/ dir wants to be under wayland/ to keep all the wayland stuff in one place, for easier maintainance. So the line in debian/bunsen-configs-wayland.install would be `wayland/wayland-sessions usr/share`
> 
> In fact all the lines in debian/bunsen-configs-wayland.install will start with wayland/

Ok, easy fix. I'll fix the PR with a "force push". No need to worry what that is - you'll see that the PR is almost unchanged except for that detail. On it shortly.

**Comment by 01micko** [comment]
See? Fixed already :)

**Comment by johnraff** [comment]
You got it!

BTW something to watch out for - at some point our symlink was named bunsenlabs-wayland-session, not bunsenlabs-session-wayland as it now is. I prefer the latter too, but our startup script bunsenlabs-session will need to be edited to reflect that.
https://github.com/BunsenLabs/bunsen-configs/blob/carbon/bin/bunsenlabs-session

For a while I was baffled why I couldn't login to Wayland...

**Comment by 01micko** [comment]
^You're right! Well at least it's fixed now (saw your commit) so this PR should be good to go. Thanks!

**Comment by johnraff** [comment]
Done.

**Comment by 01micko** [comment]
Thanks!

**Pull request merged**
