### PR TITLE
Darkened screenshots fix

### PR DESCRIPTION
**Pull request by frainfreeze**
xfce4-screenshooter not behaving properly with compositing on.

### CODE REVIEW

**Comment by ghost** [comment]
LGTM

**Comment by johnraff** [comment]
Looks good, but can we merge this into helium-dev instead of master?

**Comment by ghost** [comment]
On Sat, Sep 23, 2017 at 12:21:26AM +0000, John Crawley wrote:
> Looks good, but can we merge this into helium-dev instead of master?

I'd merge it in both master and helium-dev, because it's an important
fix.

**Comment by johnraff** [comment]
Merged.
I will patch the helium-dev branch shortly.
@frainfreeze thank you for raising this.

**Comment by ghost** [comment]
@johnraff I'll create a new package from your patch to hydrogen-master.

**Comment by johnraff** [comment]
In that case could you do an NMU bump to the version number in debian/changelog too? Thanks.

**Comment by ghost** [comment]
了解！

**Comment by ghost** [comment]
Packaged and deployed: https://github.com/BunsenLabs/bunsen-configs/commit/6768d7cb8608e895928ae39c6f728dae36e80e3a. Should land in the repository in 20 minutes.

**Pull request merged**
