### PR TITLE
skel: delete unneeded .pbuilderrc

### PR DESCRIPTION
**Pull request by ghost**
@johnraff 

These settings work for me on kernel.bunsenlabs.org. Does it  still  make sense to include a pbuilderrc or should we delete it?

### CODE REVIEW

**Comment by johnraff** [comment]
I'd say, anyone who knows how to use pbuilder isn't likely to need a preconfigured pbuilderrc. This is really a relic from when CrunchBang was Corenominal's personal system setup. Let's delete it.

There might be some other candidates for deletion.

**Comment by ghost** [comment]
@johnraff Due to my lack of usage and involvement it's hard for me to see what else in skel is obsolete. Therefore I'm not touching anything else.

I see some potential in 

 * ./applications/gdebi.desktop

I suggest that we make a decision whether what's in

* .gtkrc-2.0.mine should be active or not. If not, we could also delete that file.

What's the purpose of

  * skel/tmp? Is /tmp not magical enough?

**Comment by johnraff** [comment]
I'll have a look at **gdebi**.

**.gtkrc-2.0.mine** holds commented-out code to enable steppers, which are (or were) hidden in the BL default theme. I'd like to keep that, along with the code in  ~/.config/gtk-3.0/gtk.css. Not having steppers is an annoyance on laptops with unreliable touchpad scrolling, but the GTK theme writer felt strongly that they should be hidden by default, for appearance. Hence the commented code compromise, which should be supported by a forum HowTo eventually.

A user's **~/tmp** is more secure than /tmp because it's not world-writable, but users have to make their own arrangements to regularly empty it. Sure, let's drop it.

**Comment by johnraff** [comment]
> I see some potential in
> 
>     * ./applications/gdebi.desktop

That's a workaround for a bug in gdebi-gtk which prevents gdebi from opening a .deb file when called without a parent process, eg from a file manager, due to a somewhat arcane permissions issue. The custom .desktop file calls a wrapper script which in turn calls gdebi-gtk + args as-is. That's enough to fix the issue. https://forums.bunsenlabs.org/viewtopic.php?id=6144

Anyway, skel/tmp removed.

**Pull request merged**
