### PR TITLE
Sessions - updates for wayland

### PR DESCRIPTION
**Pull request by 01micko**
- bin/bunsen-session
- bunsen-autostart

Note that skel/.config/bunsen/autostart has no changes

### CODE REVIEW

**Comment by johnraff** [comment]
Thanks!

`skel/.config/bunsen/autostart` that I sent with [the Staging0#1 PR](https://github.com/01micko/bunsen-configs/pull/1)
does have a short Note that I added which isn't in BL. https://github.com/01micko/bunsen-configs/blob/44427e536e5776ded247bdea3001c8ebdd7e9052/skel-wbase/skel/.config/bunsen/autostart#L29

But no matter, I can easily add it at this end.

**Comment by 01micko** [comment]
I did a diff in the terminal and nothing showed! No matter though :)

**Comment by johnraff** [comment]
I'm guessing it might have been disagreement between skel/** and skel-wbase/skel/** but as you say, water under the bridge...

**Comment by 01micko** [comment]
That would be it, it's still there in the `staging0` branch, but of course `wbase` isn't merged so I didn't think to look, so my bad!

Would you like me to tidy up wbase and offer a new PR? It will only contain essentials.
- add the chown for `/var/cache/nwg-hello/cache.json` to the `postinst`
- add the link for `bunsenlabs-session-wayland -> bunsenlabs-session`
- add the `bunsenlabs-wayland.desktop`
- I suppose it needs _all_ the `debian/bunsen-configs-wbase.*` files or it will be useless

I won't put in _any_ special configs, they can go into netinstall, as they change the most often in development.

**Comment by 01micko** [comment]
I see what's happened! https://github.com/01micko/01micko.github.io/issues/7#issuecomment-2282360944

`skel/.config/bunsen/autostart`

**Comment by johnraff** [comment]
> Would you like me to tidy up wbase and offer a new PR? It will only contain essentials.
> 
>     * add the link for `bunsenlabs-session-wayland -> bunsenlabs-session`
> 
>     * add the `bunsenlabs-wayland.desktop`

Also: `autostart-wayland` and the (empty, for now) `environment-wayland`

I've added an empty wayland/ directory with subdir wayland/skel to bunsen-configs/carbon, as placeholders.
https://github.com/BunsenLabs/bunsen-configs/commit/fbd14b182e7f54b66a392b7f43dc3fb9ec55bd0e

Please feel free to put any files you want (including those mentioned above) in there to configure the apps used in the *basic* (for now) BL-carbon-wayland session: any PRs putting files under wayland/ I will accept pretty much without question. Choose whatever directory tree structure seems most easily understood by developers, though I'd suggest something similar to the parent directory. I would imagine most of it will be under wayland/skel/ or wayland/etc/ 

When we've got whatever's needed to configure a BL Wayland session that isn't already provided by bunsen-configs, then we just have to write bunsen-configs-wbase.install (or whatever the name is) and the other files in debian/, like:
>     * add the chown for `/var/cache/nwg-hello/cache.json` to the `postinst`
> 

and the package can be built.

The idea is that it's an *additional* package to bunsen-configs - not a substitute - that will come along with a meta-package to pull in the needed apps. For now, perhaps bunsen-configs-wbase could **Recommend** bunsen-meta-wbase and bunsen-meta-wbase **Depend** on bunsen-configs-wbase.

For sure there will likely be a lot of changes in both the configs and meta packages over the coming year, but as long as we try to make the system usable at each stage it should be OK.

Maybe this discussion could better be continued somewhere else? New GitHub issue, or BL forum thread?

**Comment by 01micko** [comment]
Thanks @johnraff 

> Maybe this discussion could better be continued somewhere else? New GitHub issue, or BL forum thread?

It's usually good practice to start an issue which I think I'll do. And there is no problem starting a forum thread in Dev Discussions to keep interested members in the loop that rather not interact on github.

I have one query, not being a seasoned debian developer:

> add the link for `bunsenlabs-session-wayland -> bunsenlabs-session`

Obviously it would be bad practice to add a dangling link to the /wayland/usr/bin dir so how should that be approached? Maybe you can add it? (referencing said future issue?)

I'll start work on this tonight and just add small (usually 1 file at a time) commits.

**Comment by johnraff** [comment]
> Thanks @johnraff
> 
> > Maybe this discussion could better be continued somewhere else? New GitHub issue, or BL forum thread?
> 
> It's usually good practice to start an issue which I think I'll do. 

Cool. On the BL package, I guess.

> And there is no problem starting a forum thread in Dev Discussions to keep interested members in the loop that rather not interact on github.

I might start one with a link to the issue.

> > add the link for `bunsenlabs-session-wayland -> bunsenlabs-session`
> 
> Obviously it would be bad practice to add a dangling link to the /wayland/usr/bin dir so how should that be approached? Maybe you can add it? (referencing said future issue?)

Thanks for catching that!

In fact dangling symlinks inside directory trees do work. Here's one: https://github.com/BunsenLabs/bunsen-configs/tree/carbon/skel/Pictures/wallpapers
And icon theme packages are often full of symlinks. 

But here it would feel messy, and there's a "proper" way to do it, with a debian/links file, eg: https://github.com/BunsenLabs/bunsen-configs/blob/carbon/debian/bunsen-configs.links
The first string is the content of the link (where it points) and the second is where the actual symlink is to be installed.

There was a specific reason to use a dangling symlink in skel/Pictures/wallpapers: Debian policy would have caused a link set in debian/links to be "rationalized" into a relative link, because both the symlink and its target are under /usr/. When skel is copied into $HOME the relative link would no longer work. In fact even then, an override in debian/rules was needed to preserve it as an absolute link: https://github.com/BunsenLabs/bunsen-configs/blob/carbon/debian/rules

Anyway, we can create debian/bunsen-configs-wbase.links and put it there.

**Comment by 01micko** [comment]
> Cool. On the BL package, I guess.

https://github.com/BunsenLabs/bunsen-configs/issues which is where I mean, so yes.

> But here it would feel messy, and there's a "proper" way to do it, with a debian/links file, eg:

Like this?

https://github.com/01micko/bunsen-configs/blob/44427e536e5776ded247bdea3001c8ebdd7e9052/debian/bunsen-configs-wbase.links#L9


whole file

```
usr/share/bunsen/skel/.config/mimeapps.list usr/share/bunsen/skel/.local/share/applications/mimeapps.list
usr/share/bunsen/skel/.local/share/fonts usr/share/bunsen/skel/.fonts
usr/share/bunsen/skel/.local/share/icons usr/share/bunsen/skel/.icons
usr/share/bunsen/skel/.local/share/themes usr/share/bunsen/skel/.themes
usr/lib/bunsen/configs/bl-user-setup usr/bin/bl-user-setup
usr/share/man/man1/editor.1.gz usr/share/man/man1/bl-cli-editor.1.gz
usr/share/man/man1/gdebi-gtk.1.gz usr/share/man/man1/gdebi-gtk.wrapper.1.gz
usr/share/man/man1/bunsenlabs-session.1.gz usr/share/man/man1/bunsenlabs-wayland-session.1.gz
usr/bin/bunsenlabs-session usr/bin/bunsenlabs-wayland-session
```

**Comment by johnraff** [comment]
> > But here it would feel messy, and there's a "proper" way to do it, with a debian/links file, eg:
> 
> Like this?
> 
> https://github.com/01micko/bunsen-configs/blob/44427e536e5776ded247bdea3001c8ebdd7e9052/debian/bunsen-configs-wbase.links#L9

Er, no, like this:
```
usr/bin/bunsenlabs-session usr/bin/bunsenlabs-wayland-session
```
You see, I'm looking at **bunsen-configs-wbase** as an *addon* to a Carbon X11 session, and **bunsen-configs** will already be installed (or pulled in as a dependency), so you don't need to provide - in fact *should not* provide - any of the files that come with bunsen-configs. (Bunsen-configs will be a Depends of bunsen-configs-wbase.) That's why the session files in bunsen-configs were modified the other day so as to be able to handle the Wayland session that bunsen-configs-wbase would bring in, if it were installed. bunsen-configs-wbase needs only to provide the *extra* files needed for the Wayland session. 

Concept outlined here:
https://forums.bunsenlabs.org/viewtopic.php?pid=136223#p136223

(The biggest stumbling block I can see at the moment is the DM. Neither LightDM nor greetd-cage-nwghello are perfect IMO, but I think we can find a way forward.)

---
Other thing I forgot to mention yesterday: please be careful when planning to install config files to `/etc` (ie in `wayland/etc` in the source) that they won't overwrite a file provided by the package you're configuring. (Debian doesn't allow packages to overwrite each others' files.) Some packages do provide a file in /etc expecting that sysadmins will edit it. Sysadmins can do that, but other packages shouldn't. There is a workaround using dpkg-divert, but for now I think it would be simpler in such cases to put the file in `skel/` instead, where bl-user-setup will find it and copy it to $HOME.

**Comment by 01micko** [comment]
> > > But here it would feel messy, and there's a "proper" way to do it, with a debian/links file, eg:
> > 
> > 
> > Like this?
> > https://github.com/01micko/bunsen-configs/blob/44427e536e5776ded247bdea3001c8ebdd7e9052/debian/bunsen-configs-wbase.links#L9
> 
> Er, no, like this:
> 
> ```
> usr/bin/bunsenlabs-session usr/bin/bunsenlabs-wayland-session
> ```
> 

That's exactly what [the link](https://github.com/01micko/bunsen-configs/blob/44427e536e5776ded247bdea3001c8ebdd7e9052/debian/bunsen-configs-wbase.links#L9) points to :confused: 

> You see, I'm looking at **bunsen-configs-wbase** as an _addon_ to a Carbon X11 session, and **bunsen-configs** will already be installed (or pulled in as a dependency), so you don't need to provide - in fact _should not_ provide - any of the files that come with bunsen-configs. (Bunsen-configs will be a Depends of bunsen-configs-wbase.) That's why the session files in bunsen-configs were modified the other day so as to be able to handle the Wayland session that bunsen-configs-wbase would bring in, if it were installed. bunsen-configs-wbase needs only to provide the _extra_ files needed for the Wayland session.
> 
> Concept outlined here: https://forums.bunsenlabs.org/viewtopic.php?pid=136223#p136223
> 
> (The biggest stumbling block I can see at the moment is the DM. Neither LightDM nor greetd-cage-nwghello are perfect IMO, but I think we can find a way forward.)
> 

I'm thinking drop `nwg-hello` and wait and see in the testing phase whose hardware works and whose doesn't. Perhaps a small _extra_ config package (not related to bunsen configs) could be added for users who have issues with `lightdm`. The ground work is documented for `nwg-hello/greetd` so if needed by those having issues that extra package can be installed.

> Other thing I forgot to mention yesterday: please be careful when planning to install config files to `/etc` (ie in `wayland/etc` in the source) that they won't overwrite a file provided by the package you're configuring. (Debian doesn't allow packages to overwrite each others' files.) Some packages do provide a file in /etc expecting that sysadmins will edit it. Sysadmins can do that, but other packages shouldn't. There is a workaround using dpkg-divert, but for now I think it would be simpler in such cases to put the file in `skel/` instead, where bl-user-setup will find it and copy it to $HOME.

No problem. I'm aware that packages should _not_ overwrite other packages files. I'll make sure only unique filenames are included in anything I put up for merge.

**Comment by johnraff** [comment]
> > > > ...a debian/links file, eg:
> > > 
> > > Like this?
> > > https://github.com/01micko/bunsen-configs/blob/44427e536e5776ded247bdea3001c8ebdd7e9052/debian/bunsen-configs-wbase.links#L9
> > 
> > Er, no, like this:
> > ```
> > usr/bin/bunsenlabs-session usr/bin/bunsenlabs-wayland-session
> > ```
> 
> That's exactly what [the link](https://github.com/01micko/bunsen-configs/blob/44427e536e5776ded247bdea3001c8ebdd7e9052/debian/bunsen-configs-wbase.links#L9) points to 😕
> 

Your link points specifically to line 9, but that file bunsen-configs-wbase.links holds *all* the links that already go in bunsen-configs. I'm saying that bunsen-configs-wbase should provide *only* the additional material not already shipped in bunsen-configs, ie bunsen-configs-wbase.links should hold only that single line I posted:
```
usr/bin/bunsenlabs-session usr/bin/bunsenlabs-wayland-session
```



> > You see, I'm looking at **bunsen-configs-wbase** as an _addon_ to a Carbon X11 session, and **bunsen-configs** will already be installed (or pulled in as a dependency), so you don't need to provide - in fact _should not_ provide - any of the files that come with bunsen-configs. (Bunsen-configs will be a Depends of bunsen-configs-wbase.) That's why the session files in bunsen-configs were modified the other day so as to be able to handle the Wayland session that bunsen-configs-wbase would bring in, if it were installed. bunsen-configs-wbase needs only to provide the _extra_ files needed for the Wayland session.
> > Concept outlined here: https://forums.bunsenlabs.org/viewtopic.php?pid=136223#p136223
> > (The biggest stumbling block I can see at the moment is the DM. Neither LightDM nor greetd-cage-nwghello are perfect IMO, but I think we can find a way forward.)
> 
> I'm thinking drop `nwg-hello` and wait and see in the testing phase whose hardware works and whose doesn't. 

We could proceed with lightdm for now, but let's also ship the nwg-hello, greetd and cage configs in *bunsen-configs* (not bunsen-configs-wbase). I don't think the two sets of config files will interfere with each other. If I'm understanding it right, it will be up to systemd to determine which DE will be invoked. I think even having all the packages installed would still be OK.

> Perhaps a small _extra_ config package (not related to bunsen configs) could be added for users who have issues with `lightdm`. The ground work is documented for `nwg-hello/greetd` so if needed by those having issues that extra package can be installed.
> 

Might not even be needed if the config is already in bunsen-configs - just as we ship configs for apps that aren't actually in the standard install.

> > Other thing I forgot to mention yesterday: please be careful when planning to install config files to `/etc`...
> No problem. I'm aware that packages should _not_ overwrite other packages files.

OK I should have known. :)

**Pull request merged**
